source 'https://rubygems.org'

# Core OpenTelemetry gems
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'

# AWS instrumentation
gem 'opentelemetry-instrumentation-aws_sdk'
gem 'opentelemetry-instrumentation-aws_lambda'

# AWS SDK dependencies
gem 'aws-sdk-s3'

# XML support
gem 'rexml'
